// Generated by gencpp from file my_serial_node/Agv.msg
// DO NOT EDIT!


#ifndef MY_SERIAL_NODE_MESSAGE_AGV_H
#define MY_SERIAL_NODE_MESSAGE_AGV_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace my_serial_node
{
template <class ContainerAllocator>
struct Agv_
{
  typedef Agv_<ContainerAllocator> Type;

  Agv_()
    : power(0.0)  {
    }
  Agv_(const ContainerAllocator& _alloc)
    : power(0.0)  {
  (void)_alloc;
    }



   typedef double _power_type;
  _power_type power;





  typedef boost::shared_ptr< ::my_serial_node::Agv_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::my_serial_node::Agv_<ContainerAllocator> const> ConstPtr;

}; // struct Agv_

typedef ::my_serial_node::Agv_<std::allocator<void> > Agv;

typedef boost::shared_ptr< ::my_serial_node::Agv > AgvPtr;
typedef boost::shared_ptr< ::my_serial_node::Agv const> AgvConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::my_serial_node::Agv_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::my_serial_node::Agv_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::my_serial_node::Agv_<ContainerAllocator1> & lhs, const ::my_serial_node::Agv_<ContainerAllocator2> & rhs)
{
  return lhs.power == rhs.power;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::my_serial_node::Agv_<ContainerAllocator1> & lhs, const ::my_serial_node::Agv_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace my_serial_node

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::my_serial_node::Agv_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::my_serial_node::Agv_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::my_serial_node::Agv_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::my_serial_node::Agv_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::my_serial_node::Agv_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::my_serial_node::Agv_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::my_serial_node::Agv_<ContainerAllocator> >
{
  static const char* value()
  {
    return "b61bda1d4e0075084b2082bebb59ea34";
  }

  static const char* value(const ::my_serial_node::Agv_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xb61bda1d4e007508ULL;
  static const uint64_t static_value2 = 0x4b2082bebb59ea34ULL;
};

template<class ContainerAllocator>
struct DataType< ::my_serial_node::Agv_<ContainerAllocator> >
{
  static const char* value()
  {
    return "my_serial_node/Agv";
  }

  static const char* value(const ::my_serial_node::Agv_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::my_serial_node::Agv_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 power\n"
"\n"
;
  }

  static const char* value(const ::my_serial_node::Agv_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::my_serial_node::Agv_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.power);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Agv_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::my_serial_node::Agv_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::my_serial_node::Agv_<ContainerAllocator>& v)
  {
    s << indent << "power: ";
    Printer<double>::stream(s, indent + "  ", v.power);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MY_SERIAL_NODE_MESSAGE_AGV_H
