// Generated by gencpp from file my_serial_node/Balance.msg
// DO NOT EDIT!


#ifndef MY_SERIAL_NODE_MESSAGE_BALANCE_H
#define MY_SERIAL_NODE_MESSAGE_BALANCE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace my_serial_node
{
template <class ContainerAllocator>
struct Balance_
{
  typedef Balance_<ContainerAllocator> Type;

  Balance_()
    : weight(0.0)  {
    }
  Balance_(const ContainerAllocator& _alloc)
    : weight(0.0)  {
  (void)_alloc;
    }



   typedef double _weight_type;
  _weight_type weight;





  typedef boost::shared_ptr< ::my_serial_node::Balance_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::my_serial_node::Balance_<ContainerAllocator> const> ConstPtr;

}; // struct Balance_

typedef ::my_serial_node::Balance_<std::allocator<void> > Balance;

typedef boost::shared_ptr< ::my_serial_node::Balance > BalancePtr;
typedef boost::shared_ptr< ::my_serial_node::Balance const> BalanceConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::my_serial_node::Balance_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::my_serial_node::Balance_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::my_serial_node::Balance_<ContainerAllocator1> & lhs, const ::my_serial_node::Balance_<ContainerAllocator2> & rhs)
{
  return lhs.weight == rhs.weight;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::my_serial_node::Balance_<ContainerAllocator1> & lhs, const ::my_serial_node::Balance_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace my_serial_node

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::my_serial_node::Balance_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::my_serial_node::Balance_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::my_serial_node::Balance_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::my_serial_node::Balance_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::my_serial_node::Balance_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::my_serial_node::Balance_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::my_serial_node::Balance_<ContainerAllocator> >
{
  static const char* value()
  {
    return "41998f6691705e7d3db1ca4195275ab0";
  }

  static const char* value(const ::my_serial_node::Balance_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x41998f6691705e7dULL;
  static const uint64_t static_value2 = 0x3db1ca4195275ab0ULL;
};

template<class ContainerAllocator>
struct DataType< ::my_serial_node::Balance_<ContainerAllocator> >
{
  static const char* value()
  {
    return "my_serial_node/Balance";
  }

  static const char* value(const ::my_serial_node::Balance_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::my_serial_node::Balance_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 weight\n"
;
  }

  static const char* value(const ::my_serial_node::Balance_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::my_serial_node::Balance_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.weight);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Balance_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::my_serial_node::Balance_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::my_serial_node::Balance_<ContainerAllocator>& v)
  {
    s << indent << "weight: ";
    Printer<double>::stream(s, indent + "  ", v.weight);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MY_SERIAL_NODE_MESSAGE_BALANCE_H
