local_costmap:
  global_frame: map
  robot_base_frame: base_footprint

  update_frequency: 10.0
  publish_frequency: 1.0
  transform_tolerance: 3.0  

#  static_map: false  
  rolling_window: true
  width: 3
  height: 3
  resolution: 0.05
  plugins:
    - {name: obstacle_layer,      type: "costmap_2d::VoxelLayer"}
    - {name: inflation_layer,     type: "costmap_2d::InflationLayer"}
